### ISSUE TITLE
Android Mock-ups

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#174]
## About

* **Related Issues:** 

**Mock-ups of Android Application should be prepared.**

## Tasks

- [x] Creation of draft mock-ups.
- [x] Team decision to present them to customer
- [x] Customer meeting to make sure that we're on the same page
- [x] Drawing mock-ups using web tools
- [x] Customer meetings & Iterations
- [x] Lock the design
 
Deadline: 19th October

**Comment by barisucakturk** [comment]
Considering "partly done" on locking the design in case that some changes in the next milestones.
