### ISSUE TITLE
Android Development Research

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#175]
## About

* **Related Issues:** ...
* **Other Related Links:** ...

**Android Team should learn how to develop an Android Application.**

## Tasks

- [x] Team should search for sources, and share those sources as a comment under this issue.
- [x] Team should decide on which source should be used to follow.
- [x] Each team member should inform other members about their progress.
- [x] At least one simple project should be developed by every team member.

**Comment by emreshome** [comment]
These tutorials that I found may help

- http://www.vogella.com/tutorials/Android/article.html
- https://thenewboston.com/videos.php?cat=278&video=27335
- https://www.edx.org/course/android-app-development-beginners-galileox-caad002x

**Comment by mmervecerit** [comment]
Closing since it's forgotten, we have completed all those tasks! Thanks guys! @barisucakturk @emreshome
