### ISSUE TITLE
Update Project Plan and Add Resources

### ISSUE THREAD

**Issue by ymanav** [bounswe/bounswe2017group6#190]
## About

Check the project plan and fix the date problems also add the resources to the plan.

## Tasks

- [x] Fix the dates project plan 
- [x] Add new milestones
- [x] Add the resources
