### ISSUE TITLE
Creating Sign Up and Login Pages in Android 

### ISSUE THREAD

**Issue by barisucakturk** [bounswe/bounswe2017group6#211]
## Tasks

- [x] Create to nonfunctional login and sign up pages in Android.
- [x] Change the visual part according to ideas that will come from teammates.
- [x] Convert to them as functional properly when End points come from back-end.

**Comment by barisucakturk** [comment]
First two check, last one is upcoming
