### ISSUE TITLE
Create Content/ContentType/Group Models

### ISSUE THREAD

**Issue by yhkalayci** [bounswe/bounswe2017group6#213]
## About

Creating content model with determined class model.

## Tasks

- [x] Create Content Model
- [x] Create ContentType Model
- [x] Create Group Model
