### ISSUE TITLE
Logo Creation

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#224]
## Tasks

- [x] Find logo creation website
- [x] Create Logo for Android
- [x] Embed Logo to Android Project

**Comment by mmervecerit** [comment]
<img width="129" alt="screen shot 2017-10-29 at 14 24 02" src="https://user-images.githubusercontent.com/15267081/32143072-f5c13b44-bcb4-11e7-82e5-d1d1497a7381.png">
<img width="382" alt="screen shot 2017-10-29 at 14 24 11" src="https://user-images.githubusercontent.com/15267081/32143073-f5df7cb2-bcb4-11e7-978c-35bc732be371.png">
<img width="313" alt="screen shot 2017-10-29 at 14 24 25" src="https://user-images.githubusercontent.com/15267081/32143074-f600f78e-bcb4-11e7-86c6-105999778d78.png">

**Comment by mmervecerit** [comment]
White Background Low resolution:

<img width="211" alt="screen shot 2017-10-29 at 14 28 50" src="https://user-images.githubusercontent.com/15267081/32143102-afc65876-bcb5-11e7-921e-20be09120c6b.png">
<img width="98" alt="screen shot 2017-10-29 at 14 28 58" src="https://user-images.githubusercontent.com/15267081/32143103-afeddc34-bcb5-11e7-88fc-a05769af4b30.png">
<img width="192" alt="screen shot 2017-10-29 at 14 29 03" src="https://user-images.githubusercontent.com/15267081/32143104-b015fba6-bcb5-11e7-95fb-565ed6d674af.png">

**Comment by mmervecerit** [comment]
@gokceuludogan @ymanav @buraktomruk 

What do you think?

**Comment by emreshome** [comment]
I think it looks great! Thanks merve
