### ISSUE TITLE
Android Group Profile and New Group functions

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#234]
## Tasks
- [ ] When user clicks one of the groups in the group lists, group profile page should be seen.
- [ ] In group profile page, user should be able to see group's posts, members and info about group.
- [x] If they are member of that particular group, they should be able to create a new post.
- [x] A new group should be able to created by clicking the + icon in the group list.
