### ISSUE TITLE
Update template creation modal for frontend

### ISSUE THREAD

**Issue by ymanav** [bounswe/bounswe2017group6#288]
## About

Revise the button layout and methods of template creation to give smoother experience

## Tasks

- [x] Revise the buttons.
- [x] Add a method to clear old template if the user closes the modal.
- [x] Update template creation method
- [x] Newly created template should be on the page without needing refresh
