### ISSUE TITLE
Android: Creation of User and Group Profile Page

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#315]
One can see the tasks to be completed. 

## Tasks

- [ ] Non functional User Profile Page
- [ ] Nonfunctional Group Profile Page
- [ ] Follow-Unfollow User, Group
- [ ] Functional User Profile Page
- [ ] Functional Group Profile Page

**Comment by mmervecerit** [comment]
#https://github.com/bounswe/bounswe2017group6/issues/234
