### ISSUE TITLE
Android: Add Tag system 

### ISSUE THREAD

**Issue by emreshome** [bounswe/bounswe2017group6#356]
## About

Tag system must be added to group creation, user creation and to where it is needed.
Tags must be fetched from wikidata.
Auto complete text fields must be added for this system.

## Tasks

- [ ] tag system for template creation
- [ ] tag system for groups
- [ ] tag system for users
