### ISSUE TITLE
Android: Final Deliverables

### ISSUE THREAD

**Issue by mmervecerit** [bounswe/bounswe2017group6#436]
Final Report ->[ShareLatex]( https://www.sharelatex.com/6887327871yxqqvjwqdqww ) , HARD COPY NEEDED

Complete the tasks below, put the files into drive: [Drive Link](https://drive.google.com/open?id=1QL9EUWJE3JRB0ghrvNJckQAGV9fv5wrw)

## Tasks
- [x] Android Manual (User & System) -> Upload to Github, Final Report
- [x] "Readme" file that contains instructions on how to deploy and configure your web and Android applications - Drive
- [x] .apk file containing the Android solution -Drive
- [x] Final version of code, documented and including unit tests - Drive
- [x] User test cases and testing results (including at least 5 non-member test results) -- scanned - Drive
- [x] Project video for Android - Drive
- [x] Project Plan Android - Drive - Final Report
- [x] Design of Android - Final Report
- [x] Final project assessment  assesses the whole process such as lessons learned - Final Report
- [x] A summary of coding work done by each team member (In tabular format) - Final Report

**Comment by barisucakturk** [comment]
User test cases are finished, let's work on other task.
